language: node_js
node_js:
  - 8
  - 10
  - stable
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi  
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - gcc-4.8
       - g++-4.8
